name: sam_lidar
dependencies:
  - python>=3.10.0
  - conda-forge::pytorch>=2.5.1
  - fiona>=1.9.6
  - fvcore>=0.1.5,<0.1.6
  - geopandas
  - git
  - ipykernel
  - IPython
  - laspy
  - lazrs-python
  - conda-forge::libvorbis
  - matplotlib
  - numpy>=1.24.4
  - omegaconf
  - opencv
  - pandas
  - pip
  - pytorch_lightning>=2.1.0
  - rasterio>=1.4.3
  - rtree
  - scikit-learn
  - scipy>=1.5.2
  - slidingwindow
  - supervision
  - xmltodict